### ISSUE TITLE
Wrong key

### ISSUE THREAD

**Issue by AmritaHanna** [cyberscribe/login-recaptcha#15]
I have submitted wrong key. How can I change it? I have closed the window. And now I cannot find how to change the settings. Thank you

**Comment by WSP-webmaster** [comment]
Best to deactivate the plugin using an FTP client, (rename the folder with
a period in front of it), log into your WordPress site. rechange the folder
through the FTP client again to remove the period, refresh the plugin page,
reactive it, then go to its setting option and correctly copy past the two
keys from the recaptcha site.

Hope that helps.

Thank you,
Webmaster A.Logan
www.WebStudioProductions.com
Office: 508-598-5710

This e-mail is confidential, if you are not the intended recipient, do not
retain/disclose it and please return it to us.
We virus scan and monitor all e-mails but are not responsible for any
damage caused by a virus/alteration of our e-mail by a third party after
sending.
Help save paper, please think before printing this e-mail.

**Comment by AmritaHanna** [comment]
I have no idea how to do this. I am just a regular user not an IT. Do 
you perhaps have more detailed description on how to do this for 
dummies?

This is my level:
What is FTP client?
What folder and what is a period?
I am completelly lost...

Thank you

---
Prajem príjemný deň

Amrita Hanna Slaninková
0903 797 188
www.amrita.sk

Dňa 2019-05-02 18:36 WSP-webmaster napísal(a):

**Comment by WSP-webmaster** [comment]
Are you still inside the admin part of your wordpress site or are you
unable to log in?

Thank you,
Webmaster A.Logan
www.WebStudioProductions.com
Office: 508-598-5710

This e-mail is confidential, if you are not the intended recipient, do not
retain/disclose it and please return it to us.
We virus scan and monitor all e-mails but are not responsible for any
damage caused by a virus/alteration of our e-mail by a third party after
sending.
Help save paper, please think before printing this e-mail.

**Comment by AmritaHanna** [comment]
I can login, because fortunatelly I have put my IP address on the white 
list.
But others cannot. But I am in.

---
Prajem príjemný deň

Amrita Hanna Slaninková
0903 797 188
www.amrita.sk

Dňa 2019-05-02 18:54 WSP-webmaster napísal(a):

**Comment by WSP-webmaster** [comment]
Assuming you're logged into an admin level account, Are you able to locate
the plug-in along the left (gray) side of the admin backend? If so click on
the plug-in name.

Thank you,
Webmaster A.Logan
www.WebStudioProductions.com
Office: 508-598-5710

This e-mail is confidential, if you are not the intended recipient, do not
retain/disclose it and please return it to us.
We virus scan and monitor all e-mails but are not responsible for any
damage caused by a virus/alteration of our e-mail by a third party after
sending.
Help save paper, please think before printing this e-mail.

**Comment by AmritaHanna** [comment]
I am in the Plug in section.
It is not possible to click on any name of the plug in. On this one I 
can click only to "deactivate", then "Robert Peake" and "show details".

There is nothing else to click on.

---
Prajem príjemný deň

Amrita Hanna Slaninková
0903 797 188
www.amrita.sk

Dňa 2019-05-02 19:16 WSP-webmaster napísal(a):

**Comment by WSP-webmaster** [comment]
Look more left, in the gray side bar, where the current word "plugin" is
selected, in the area where pages and posts and the word comment is, look
near the end of that list for the plug-in name, also check under the word
"setting" along the side in the same gray area.

Thank you,
Webmaster A.Logan
www.WebStudioProductions.com
Office: 508-598-5710

This e-mail is confidential, if you are not the intended recipient, do not
retain/disclose it and please return it to us.
We virus scan and monitor all e-mails but are not responsible for any
damage caused by a virus/alteration of our e-mail by a third party after
sending.
Help save paper, please think before printing this e-mail.

**Comment by AmritaHanna** [comment]
Ahaaaaa... Got it! :DDDDD
Thank you so much. I have changed the keys and now it is working! It was 
under the settings.
Thank you for your kind navigation...


---
Prajem príjemný deň

Amrita Hanna Slaninková
0903 797 188
www.amrita.sk

Dňa 2019-05-02 19:25 WSP-webmaster napísal(a):

**Comment by WSP-webmaster** [comment]
Np, glad to be of help :)

Thank you,
Webmaster A.Logan
www.WebStudioProductions.com
Office: 508-598-5710

This e-mail is confidential, if you are not the intended recipient, do not
retain/disclose it and please return it to us.
We virus scan and monitor all e-mails but are not responsible for any
damage caused by a virus/alteration of our e-mail by a third party after
sending.
Help save paper, please think before printing this e-mail.
