### ISSUE TITLE
xml-prc bypass error

### ISSUE THREAD

**Issue by rleomartin** [cyberscribe/login-recaptcha#18]
I am getting the following error: Login NoCaptcha was bypassed on login page: xmlrpc.php.

I have version 1.6.4 of the plugin installed. Wordpress version 5.2.3, PHP 7.0.33 and MySQL 5.7.27

**Comment by cyberscribe** [comment]
The plugin is unable to hook in to xmlrpc-based logins to authenticate them, because they are programmatic (i.e. not presenting a user with screens). This is therefore a warning that this method is open to possible attack, and that the plugin will not defend you against an attack against xml-rpc based login attacks.
