### ISSUE TITLE
Works for admin login but doesn't for regular user login

### ISSUE THREAD

**Issue by hollygirouard** [cyberscribe/login-recaptcha#4]
Hi there! 

Thanks for creating this plugin. I'm having some trouble on a client's site. The plugin works like a charm for admin users but for a regular user, you can bypass the recaptcha and continue to login without checking the box. I don't have any errors so it's difficult for me to troubleshoot. Any advice here? 

Thanks in advance! 
-Holly

**Comment by cyberscribe** [comment]
Hi Holly,

I'm confused by this. I know Google Authenticator works on a per-user basis, but this plugin is designed to hook into *all* login requests and deny them if the reCaptcha has failed.

I know it sounds silly--but are you sure you have the right plugin? I've not seen this behaviour before. If so, any more that you can tell me would be greatly appreciated.

Best,
Robert

**Comment by cyberscribe** [comment]
p.s. to say I'm particularly surprised that users can log in without checking the box, since there is javascript in place to disable the login button until you check the box. Most normal users don't know how to bypass the javascript to force the button to work...

**Comment by WSP-webmaster** [comment]
Sorry to chime in but I had a few thoughts on this issue. Is the login page
that the clients are using aka regular user different from the page where
the admins login or are all users logging in through WP-login.PHP?

**Comment by cyberscribe** [comment]
Thanks for chiming in @WSP-webmaster -- that's a good question. I don't believe reCaptcha is designed to show up on any custom login pages besides the standard wp-admin/wp-login.php pages, but I could be mistaken. Perhaps there is another login page being created by another plugin that ends up hooking in the checkbox but not the check that the box got checked?

**Comment by hollygirouard** [comment]
Thanks for the fast replies @cyberscribe  and @WSP-webmaster! Yes - I'm fairly certain it's the right plugin - here's a screenshot for verification https://screencast.com/t/VdnaTwrP7 (I'll change those keys later). I didn't build this site, but I'm also somewhat confident that this is the default WP login. Here's the code: https://screencast.com/t/PtS602pArL

**Comment by cyberscribe** [comment]
Thanks @hollyewhite for this. Based on code like `get_permalink(53);`, which is some kind of hard-coding to get the link to a specific page on a specific site, this looks like custom code that is generating the login page here, not the standard wp-login.php. It may be part of a plugin package that you can inspect and, if it's a third-party, you might be able to convince them to support checking the reCaptcha checkbox using the standard WordPress login checks instead of their custom approach. Or, if you've inherited this code, it may be custom code that the previous person wrote. 

Sadly, it's a bit beyond the scope of the standard plugin, which is designed to work with the standard wp-login.php functionality, to be able to dig much deeper into this. @WSP-webmaster may have other ideas here, though.

**Comment by WSP-webmaster** [comment]
You are correct Robert I ran into the same problem when I try to use this
plugin on a custom login page I was able to make the recaptcha box display
but had to go back to the custom login page plug-in author to add the
authentication check functionality.

Another option could be to go directly to Google recaptcha website, their
help documents might tell you how to add the coding necessary to check the
recaptcha check box.

I hope you find this information helpful.

**Comment by hollygirouard** [comment]
Thanks @WSP-webmaster  and @cyberscribe.

Hmm, so that redirect is just saying if they're logged in go to their profile page if not, activate the WP login. From what I can tell there aren't any plugins and it is using the standard functionality. I mean, I have been wrong before but usually those things are really easy to find...

The interesting thing is that upon installation it works like a charm then later on my client comes back saying it is broken.

**Comment by cyberscribe** [comment]
My only other thought given the "works fine, then later is broken" scenario
is whether some form of caching is in play...

**Comment by WSP-webmaster** [comment]
I don't wish to come across as distrusting your client Holly but have you
personally been able to replicate or witness what your client is stating or
seeing regarding this incorrect recaptcha login functionality?

On Nov 1, 2017 11:40 AM, "Holly" <notifications@github.com> wrote:

Thanks @WSP-webmaster <https://github.com/wsp-webmaster> and @cyberscribe
<https://github.com/cyberscribe>.

Hmm, so that redirect is just saying if they're logged in go to their
profile page if not, activate the WP login. From what I can tell there
aren't any plugins and it is using the standard functionality. I mean, I
have been wrong before but usually those things are really easy to find...

The interesting thing is that upon installation it works like a charm then
later on my client comes back saying it is broken.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cyberscribe/login-recaptcha/issues/4#issuecomment-341144372>,
or mute the thread

**Comment by hollygirouard** [comment]
Caching was my initial thought too @cyberscribe but then I tried Incognito and I can replicate it in FFDE and Chrome so theoretically it should work. 

@WSP-webmaster I think that answers your question too. :) In a previous life I worked support so step one - replicate. ;)

**Comment by hollygirouard** [comment]
I can continue to do some troubleshooting and follow up. I don't want to take too much of your time. I was just hoping it might be something silly I'm missing.

**Comment by WSP-webmaster** [comment]
Just to make sure that I'm understanding what has been covered so far
correctly both you and your client are trying to login using the exact same
login page, when you as an admin try to log in the recaptcha if not checked
is stopping the login process but if the username and password are changed
to your clients username and password the recaptcha check box is not
stopping the login process. The only thing that it's changing on the page
is whose username and password are entered.

Is this a fair and accurate summary?

**Comment by hollygirouard** [comment]
Hmm, maybe I didn't explain that well. 

Instance 1: You're an admin - you login on the backend using wp-admin. The recaptcha works there and you cannot bypass it. 

Instance 2: You're an end user. The end recaptcha is there but you are able to bypass it.

**Comment by WSP-webmaster** [comment]
It sounds like this is circling back to using a custom login page as the
issue for the client login process and not the standard WordPress login
page (wp-login.php)

Here is a link to a YouTube video that I found that may help you implement
Google recaptcha into your custom login page.

https://youtu.be/xByblMJsA8s
I did a search on YouTube using the term "how to add Google recaptcha
version 2 to my website"

I hope you find this information helpful :)

**Comment by hollygirouard** [comment]
Thank you @WSP-webmaster
